.\" Manpage for rerun_that
.TH man 1 "14 July 2022" "202304231750-git" "rerun_that"

.SH NAME
rerun_that

.SH DESCRIPTION


.SH SYNOPSIS
rerun_that [options] [command]

.SH OPTIONS
.TP
.B \-\-help
Display the full help.
.TP
.B \-\-version
Display current version.
.TP
.B \-\-config
Create user settings file.
.TP
.B \-\-options
Show all availabe options.
.TP
.B \-\-dir
Change current directory
.TP
.B \-\-debug
Output debugging information.
.TP
.B \-\-raw
Removes all formatting

.SH EXAMPLES
.TP
.B rerun_that \-\-help

.SH FILES
.TP
.I
~/.config/myscripts/rerun_that/settings.conf
.TP
.I
/usr/local/bin/rerun_that

.SH TODO
Better documentation

.SH LICENSE
LICENSE.md

.SH BUGS
No known bugs.

.SH REPORTING BUGS
https://github.com/casjay-dotfiles/issues

.SH AUTHOR
Currently maintained by Jason Hempstead <jason@casjaysdev.pro>
