#!/usr/bin/env sh
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version           :  202304261931-git
# @@Author           :  Jason Hempstead
# @@Contact          :  git-admin@casjaysdev.pro
# @@License          :  LICENSE.md
# @@ReadME           :  .xserverrc --help
# @@Copyright        :  Copyright: (c) 2023 Jason Hempstead, Casjays Developments
# @@Created          :  Wednesday, Apr 26, 2023 20:04 EDT
# @@File             :  .xserverrc
# @@Description      :  X server init file
# @@Changelog        :  newScript
# @@TODO             :  Refactor code
# @@Other            :
# @@Resource         :
# @@Terminal App     :  no
# @@sudo/root        :  no
# @@Template         :  shell
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# shell check options
# shellcheck disable=SC2317
# shellcheck disable=SC2120
# shellcheck disable=SC2155
# shellcheck disable=SC2199
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Return if already sourced
[ "$IS_SOURCED_XSESSION" != 1 ] || return
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[ -z "$IS_SOURCED_XPROFILE" ] && [ -f "$HOME/.xprofile" ] && . "$HOME/.xprofile"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
export IS_SOURCED_XSESSION=1
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# end
