#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 031420210104-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : LICENSE.md
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Sunday, Mar 14, 2021 06:20 EDT
# @File          : countdown
# @Description   :
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_countdown() {
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local OPTS="--help --version"
  local ARRAY="$(echo {1..9}{0..9}{0..9})"

  _init_completion || return

  if [[ ${cur} == -* ]] ; then
    COMPREPLY=( $(compgen -W '${OPTS}' -- ${cur}) )
  else
  case $prev in
  *)
    compopt -o nospace
    COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
    #return 0
    ;;
  esac
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _countdown countdown
