#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 031420210104-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : LICENSE.md
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Sunday, Mar 14, 2021 06:20 EDT
# @File          : prompt
# @Description   :
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_prompt() {
  local CONFDIR="$HOME/.config/dmenu/prompts"
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local FUNCTIONSDIR="${HOME/.local/share/CasjaysDev/functions}"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local SHOW_COMP_OPTS=""
  local SHORTOPTS="-h -v -f"
  local LONGOPTS="--help --version --file"
  local ARGS="${SHORTOPTS} ${LONGOPTS}"
  local ARRAY="show-commands"
  local FILEDIR="$(find -L "$HOME/.config/dmenu/prompts" -maxdepth 1 -type f,l | sed 's#'$CONFDIR/'##g')"
  mkdir -p "$HOME/.config/dmenu/prompts"

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o ${SHOW_COMP_OPTS_SEP}
  fi

  if [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${ARGS}' -- ${cur}))
  else
    case $prev in
      -f | --file)
        COMPREPLY=($(compgen -W '$FILEDIR' -- "${cur}"))
        ;;
      *)
      if [ "$ARRAY" = "show-commands" ]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" = "show-none" ]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [ "$ARRAY" = "show-_filedir" ]; then
        _filedir
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      fi
      return 0
      ;;
    esac
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _prompt -o default prompt
