#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 031620212329-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.com
# @License       : LICENSE.md
# @ReadME        : setver --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, CasjaysDev
# @Created       : Tuesday, Mar 16, 2021 23:46 EDT
# @File          : setver
# @Description   :
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_setver() {
  local CONFDIR="$HOME/.config/misc/settings/setver"
  local CASJAYSDEVDIR="${CASJAYSDEVDIR:-/usr/local/share/CasjaysDev/scripts}"
  local FUNCTIONSDIR="${HOME/.local/share/CasjaysDev/functions}"
  local SEARCHCMD="$(find -L $CONFDIR -maxdepth 3 -type f 2>/dev/null | sed 's#'$CONFDIR/'##g' | grep '^' || return 1)"
  local cur prev words cword
  local cur="${COMP_WORDS[COMP_CWORD]}"
  local SHOW_COMP_OPTS=""
  local DEFAULTOPTS='show dns create '
  local SHORTOPTS="-h -v -f -d -c"
  local LONGOPTS="--help --version --file --config --dir"
  local ARGS="${SHORTOPTS} ${LONGOPTS}"
  local ARRAY="$DEFAULTOPTS"

  _init_completion || return

  if [ "$SHOW_COMP_OPTS" != "" ]; then
    local SHOW_COMP_OPTS_SEP="$(echo "$SHOW_COMP_OPTS" | tr ',' ' ')"
    compopt -o ${SHOW_COMP_OPTS_SEP}
  fi

  if [[ ${cur} == -* ]]; then
    COMPREPLY=($(compgen -W '${LONGOPTS}' -- ${cur}))
  else
    case $prev in
    *)
      if [ "$ARRAY" = "show-commands" ]; then
        COMPREPLY=($(compgen -c -- "${cur}"))
      elif [ "$ARRAY" = "show-none" ]; then
        COMPREPLY=($(compgen -W '' -- "${cur}"))
      elif [ "$ARRAY" = "show-_filedir" ]; then
        _filedir
      elif [ "$ARRAY" != "" ]; then
        COMPREPLY=($(compgen -W '${ARRAY}' -- "${cur}"))
      elif [ -n "$OPTS" ]; then
        COMPREPLY=($(compgen -W '${OPTS}' -- "${cur}"))
      fi
      return 0
      ;;
    esac
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _setver setver
