#!/usr/bin/env bash
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
##@Version       : 202108030333-git
# @Author        : Jason Hempstead
# @Contact       : jason@casjaysdev.pro
# @License       : LICENSE.md
# @ReadME        : venv --help
# @Copyright     : Copyright: (c) 2021 Jason Hempstead, Casjays Developments
# @Created       : Sunday, Dec 19, 2021 10:54 EST
# @File          : venv
# @Description   : venv completion script
# @TODO          :
# @Other         :
# @Resource      :
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_venv_completion() {
  local venv_name="" venv_dir="" venv_projects=""
  local venv_dir="${SETV_VIRTUAL_DIR_PATH:-$PWD}/$venv_dir"
  [ -f "$PWD/.venv_name" ] && venv_name="$(<"$PWD/.venv_name")" || venv_name="$(basename "$PWD")"
  venv_dir="${SETV_VIRTUAL_DIR_PATH/$venv_name:-$PWD/.venv}"
  [ -f "$PWD/.venv_name" ] && venv_dir="$(<"$PWD/.venv_name")"
  venv_projects="$([ -n "$SETV_VIRTUAL_DIR_PATH" ] && find "$SETV_VIRTUAL_DIR_PATH/" -maxdepth 1 -type d -printf "%P\n" 2>/dev/null | grep -v '^$' || echo '')"
  #[ "$word" = "delete" ] && COMPREPLY=($(compgen -W '${venv_projects}' -- "$cur"))
  if [ -n "$VIRTUAL_ENV" ]; then
    COMPREPLY=($(compgen -W 'deactivate' -- "$cur"))
  elif [ -f "$venv_dir/bin/activate" ]; then
    COMPREPLY=($(compgen -W 'activate delete' -- "$cur"))
  elif [ -n "$venv_projects" ]; then
    COMPREPLY=($(compgen -W 'create delete ${venv_projects}' -- "$cur"))
  fi
} &&
  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  # enable completions
  complete -F _venv_completion -o default venv
